//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPApp.Resources.Strings.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSP Desktop.
        /// </summary>
        internal static string CSSPDesktop {
            get {
                return ResourceManager.GetString("CSSPDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CSSP Desktop application will let you:.
        /// </summary>
        internal static string CSSPDesktopApplicationWillLetYou {
            get {
                return ResourceManager.GetString("CSSPDesktopApplicationWillLetYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSSP Desktop Description.
        /// </summary>
        internal static string CSSPDesktopDesc {
            get {
                return ResourceManager.GetString("CSSPDesktopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Canadian Shellfish Sanitation Program (CSSP).
        /// </summary>
        internal static string CSSPFullText {
            get {
                return ResourceManager.GetString("CSSPFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string CurrentLanguageText {
            get {
                return ResourceManager.GetString("CurrentLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Make calculation using Box Model and Visual Plumes,.
        /// </summary>
        internal static string MakeCalculationUsingBoxModelAndVP {
            get {
                return ResourceManager.GetString("MakeCalculationUsingBoxModelAndVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact a site administrator listed below for access.
        /// </summary>
        internal static string PleaseContactASiteAdministratorListedBelowForAccess {
            get {
                return ResourceManager.GetString("PleaseContactASiteAdministratorListedBelowForAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Setup and run MIKE scenarios and store inputs and results.
        /// </summary>
        internal static string SetupAndRunMIKEScenariosAndStoreInputsAndResults {
            get {
                return ResourceManager.GetString("SetupAndRunMIKEScenariosAndStoreInputsAndResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - View and update the waste water treatment plants and the lift stations information,.
        /// </summary>
        internal static string ViewAndUpdateWWTPInfo {
            get {
                return ResourceManager.GetString("ViewAndUpdateWWTPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Visualize and manage Marine Water Quality Monitoring Information.
        /// </summary>
        internal static string VisualizeAndManageMarineWQInfo {
            get {
                return ResourceManager.GetString("VisualizeAndManageMarineWQInfo", resourceCulture);
            }
        }
    }
}
